steps:

    - id: go_version
      name: "gcr.io/cloud-builders/go"
      args: ["version"]
      env: ["GOPATH=."]

    - id: "Rodando Go Env"
      name: 'gcr.io/cloud-builders/go'
      args: ['env']
      env: ["GOPATH=."]
   
    - id: "Rodando Go Test"
      name: 'gcr.io/cloud-builders/go'
      args: ['go','test']

    - id: "Rodando Go Build"
      name: 'gcr.io/cloud-builders/go'
      args: ['go','build', 'main.go']
    
    